include( "${BUILDER_ROOT}/CodecsFunctions.cmake" )

set( CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} " -DMFX_PRODUCT_NAME='\"${MFX_PRODUCT_NAME}\"'")
set( CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} " -DMFX_COPYRIGHT='\"${MFX_COPYRIGHT}\"'")

set( CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} ${MFX_CXX_FLAGS} )
string (REPLACE ";" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")




