//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msdk_analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("msdk_analyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intel\Media_SDK_Analyzer\.
        /// </summary>
        internal static string app_data_folder {
            get {
                return ResourceManager.GetString("app_data_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {9B540B39-3730-4cc0-B753-16302ED006D2}.
        /// </summary>
        internal static string msdk_analyzer_guid {
            get {
                return ResourceManager.GetString("msdk_analyzer_guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msdk_analyzer_session.
        /// </summary>
        internal static string msdk_analyzer_session_name {
            get {
                return ResourceManager.GetString("msdk_analyzer_session_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Intel\MediaSDK.
        /// </summary>
        internal static string msdk_registry_key {
            get {
                return ResourceManager.GetString("msdk_registry_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\Software\Intel\MediaSDK\Debug\Analyzer\.
        /// </summary>
        internal static string target_folder_key {
            get {
                return ResourceManager.GetString("target_folder_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        internal static string target_folder_value {
            get {
                return ResourceManager.GetString("target_folder_value", resourceCulture);
            }
        }
    }
}
